### ISSUE TITLE
"fields" and "columns" parameters missing?

### ISSUE THREAD

**Issue by Zebble** [spinen/connectwise-company-php-client#1]
Looks like "fields" is acceptable for pulling specific fields from a non-report API GET, and "columns" can be used for reports.  Any chance of adding these parameters?

I tested by hardcoding a "fields" within CompaniesApi.php, and it works as expected, but it does seem to pull in all field names, but non-specific fields are blank.

I assume this was simply missing from ConnectWise's own reference API code?

**Comment by jimmypuckett** [comment]
We build these calls automatically off of their swagger file.  We have recently updated our local CW install & was planning on rebuilding them.  Is next week OK, or do you need/want them sooner?

**Comment by Zebble** [comment]
No rush!  That was a fast reply, thanks!

I assume CW has updated their swagger file to include the fields and columns parameters or is this something we need to notify them to add?

**Comment by jimmypuckett** [comment]
Their docs on their site is built with the same swagger files, so if the column is in their docs, then it will be in the generated client.

**Comment by Zebble** [comment]
Those parameters are missing from the individual API call docs, but do show up in the general overview docs.

Appear here, under the "Get" subsection:

https://developer.connectwise.com/Manage/Developer_Guide

But don't appear anywhere else that I can see.

**Comment by Zebble** [comment]
Details on the "fields" and "columns" parameters:

https://developer.connectwise.com/Manage/Developer_Guide#Partial_Responses

**Comment by jimmypuckett** [comment]
@Zebble, we thought that we had a "quick fix" & just broke the code that is in master.  Don't do a composer update.  Will push up fix shortly.

**Comment by Zebble** [comment]
Thanks!  FYI, I've been using your pre-built versions.  I'm a composer noob.

**Comment by jimmypuckett** [comment]
We have pushed up a new version of the library with the latest build from their swagger files.  Please let us know if that does not address your issue.  Feel free to reopen it if not properly addressing your needs.

**Comment by Zebble** [comment]
Fields/Columns still don't seem to be parameters that can be used.  This update also seems to have broken something.  Seems to be related to namespace possibly being doubled up?

eg.  from CompaniesApi.php:

namespace Spinen\ConnectWise\Clients\Company\Spinen\ConnectWise\Clients\Company\Api;

Resulting in an error when trying to create a new object using the documentation:

PHP Fatal error:  Uncaught Error: Class 'Spinen\ConnectWise\Clients\Company\Api\CompaniesApi' not found in /var/www/html/xsp/xsp.php:30
Stack trace:
#0 {main}
  thrown in /var/www/html/xsp/xsp.php on line 30

**Comment by jimmypuckett** [comment]
Ya, the doubled up namespace was what we broke. We pushed a newer version. Don't sure why you still have old version.  Try to grab fresh copy of the code.

**Comment by Zebble** [comment]
Pulled a fresh copy of connectwise-company-php-client and same issue.

git clone https://github.com/spinen/connectwise-company-php-client.git

Your online code for these prebuilt versions are still showing the double-namespace, for example:

https://github.com/spinen/connectwise-company-php-client/blob/master/lib/Api/CompaniesApi.php

**Comment by jimmypuckett** [comment]
@Zebble You are correct.  We fixed the double namespace in the documentation, but not the actual files.  Fixing it now...

**Comment by ssfinney** [comment]
Abandoned
